cluster.name: "my-search-cluster"
node.name: "es-node05"


network.host: "0.0.0.0"
http.port: 9200
transport.port: 9300

discovery.seed_hosts: ["es-node01:9300", "es-node02:9300", "es-node03:9300", "es-node04:9300", "es-node05:9300"]
cluster.initial_master_nodes: ["es-node01", "es-node02", "es-node03"]

gateway.recover_after_data_nodes: 3

xpack.security.enabled: false
